version: "3"

services:
  db:
    image: postgres:10
    ports:
    - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      POSTGRES_DB: bugs
      POSTGRES_USER: bugs
      POSTGRES_PASSWORD: bugs
      